CREATE TABLE table1(key INT,value INT);
CREATE TABLE table2(singlecol INT);
INSERT INTO table1 VALUES (1, 1);
INSERT INTO table1 VALUES (2, 2);
INSERT INTO table1 VALUES (10, 3);
INSERT INTO table1 VALUES (11, 4);
INSERT INTO table1 VALUES (12, 5);
INSERT INTO table1 VALUES (21, 6);
INSERT INTO table1 VALUES (121, 7);